# Generated by Django 6.0.1 on 2026-03-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_optimization_software', '0002_alter_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reorder_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
